### ISSUE TITLE
bump pycryptodome version

### ISSUE THREAD

**Issue by MementoRC** [ebellocchia/bip_utils#120]
Would it be possible to bump pycryptodome version (ideally to 3.20)? The conda-recipe fails because version 3.6.6 available in conda-forge is incompatible with python >3.8

The alternative of repopulating 3.6.6 for the newest python version may be difficult, though I will also post a request

Are you interested in being added as a maintainer of the conda-forge recipe

**Comment by ebellocchia** [comment]
Ok I'll do it

**Comment by MementoRC** [comment]
Please, wait a bit longer, I am seeing that ecdsa=0.16.* is failing the tests on a clean environment. In order to build the conda-forge recipe it would require to have esdca and pynacl bumped as well. These packages are a bit old and conda-forge does not particularly back-populate them

Do you have concerns in updating these packages?

It seems that it would need - I can test to find the oldest pycryptodome that passes:
    - ecdsa >=0.17.*
    - pycryptodome =3.20.*
    - pynacl =1.5.*

**Comment by ebellocchia** [comment]
Is there a minimum Python version for the conda recipe? Maybe I can leave the current ones for older Python versions using environment markes, for example:

```
ecdsa~=0.15; python_version < '3.11'
ecdsa~=0.17; python_version >= '3.11'
.and so on...
```

**Comment by MementoRC** [comment]
Yes, this is possible, however the tests fail with `ecdsa<0.17`. The minumum version in conda-forge is `pycryptodome>=3.15`
I tested with python 3.10 and ecdsa=0.17.*

Note that I could simply not run the tests when I create the recipe, but I usually prefer to run the tests after the created artifact is installed in a clean environment

**Comment by MementoRC** [comment]
For conda itself, this would work (with `environment.yml`) but the goal of the recipe for `conda-forge` (which is a repository of packages installable within a conda environment) is to strictly adhere to the official requirement of the upstream package, either the PYPI or the official github repo (this is how I built the recipe for your package).
When the package is built, the conda-forge build process verifies that the requirements that I put in the recipe match the one you set in `requirement.txt`
```
Encountered problems while solving:
  - package bip-utils-2.9.1-py311h38be061_0 requires ecdsa 0.16.*, but none of the providers can be installed
```
In order to create an environment, say for python-3.12, all the packages have to be installable with python-3.12 ABI. This is why pycryptodome 3.6.6 cannot be used, it is a binary package that only has python<3.9

The problem with ecdsa is different, the tests fail with:
```
python -m unittest discover
........................................F....................................................................................................................................................................................................F................................................................................................................................................................................F............................................................................
======================================================================
FAIL: test_nist256p1 (tests.ecc.test_ecc.EccTests.test_nist256p1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../bip_utils/bip_utils/ecc/nist256p1/nist256p1_point.py", line 53, in FromBytes
    return cls(ellipticcurve.PointJacobi.from_bytes(curve_256,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'PointJacobi' has no attribute 'from_bytes'
```

**Comment by ebellocchia** [comment]
Ok, let me give a check to all requirements and test them

**Comment by ebellocchia** [comment]
With these requirements I didn't get errors from 3.7 to 3.12, you can try if they work:

```
cbor2~=5.1
coincurve>=15.0.1,<19.0.0; python_version < '3.12'
coincurve>=19.0.0,<20.0.0; python_version >= '3.12'
crcmod~=1.7
ecdsa~=0.17
ed25519-blake2b>=1.4.1,<2.0.0
pycryptodome~=3.8
pynacl~=1.4
py-sr25519-bindings>=0.1.3,<2.0.0
```

**Comment by MementoRC** [comment]
This is not going to work either. The lowest version of `pycryptodome` that will work is `~=3.15` and `pynacl~=1.5`
Actually, `coincurve` does not need to change, the reviewer I am working with understand that `19.0.0` is API compatible with `18.0.0` and after a few check will approve the recipe
So the critical issues for conda-forge are pycryptodome and pynacl (and ecdsa that you have updated already)

So, another solution would be for me to use my fork with the version updates that I need and create the recipe based on my fork. Obviously, I do not prefer this solution. But it would not require you to change the requirements that you feel confident with

Are there issues with these releases of `pycryptodome` and `pynacl`?

**Comment by ebellocchia** [comment]
I changed `coincurve` to make it work with older Python versions, not for conda.
But I don't get why `pycryptodome` and `pynacl` cause problems on conda if they work on pip, I tried 3.8 and 1.4 with all Python versions with no issues.

**Comment by MementoRC** [comment]
conda-forge requires `pynacl` and `pycryptodome` versions to be available on conda-forge. A recipe requires all the dependencies to be available on conda-forge, this way it guarantees a consistent environment is maintained when `bip-utils` is installed within a conda environment. conda-forge does not consider pip packages

Currently, the available version for those 2 packages are inconsistent with python >3.8 ABI and thus cannot be used within a python 3.8 conda environment, thus the recipe fails

Clearly, you seem very uncomfortable updating your requirements and I am the one interested in a conda-forge recipe, so the solution seems to be to use my fork to create the recipe and make the extra work of maintaining consistency (but for requirements) with your project. This is perfectly fine. In order to get `coincurve` as a conda-forge recipe, ofek and I had to do a lot of work when his project worked perfectly well with pip, so it is very understandable that not every author is interested in conda-forge, nor has the time to invest in doing this extra work

For now, et's agree that I will use my fork, follow your updates and who knows, maybe in a few months the issues will be resolved and I'll change the recipe to point to your repo - Does that sound like a good compromise?

**Comment by ebellocchia** [comment]
No that's ok, I can update them, I just wanted to fully understand how conda works.
That's the file after my last tests:

```
cbor2~=5.1
coincurve>=16.0.0,<19.0.0; python_version < '3.11'
coincurve>=18.0.0,<20.0.0; python_version == '3.11'
coincurve>=19.0.0,<20.0.0; python_version >= '3.12'
crcmod~=1.7
ecdsa~=0.17
ed25519-blake2b>=1.4.1,<2.0.0
pycryptodome~=3.15
pynacl~=1.5
py-sr25519-bindings>=0.1.3,<2.0.0; python_version < '3.10'
py-sr25519-bindings>=0.1.4,<2.0.0; python_version == '3.10'
py-sr25519-bindings>=0.2.0,<2.0.0; python_version >= '3.11'
```

**Comment by ebellocchia** [comment]
Hi, I updated the requirements

**Comment by MementoRC** [comment]
Hi, Thanks.

The situation seems more complicated than I realized. It seems that there is a collision between the version of `ecdsa` installed in the environment and the `PointJacobi` class in `bip-utils` during the tests.

So, for now, my fork has a conda-friendly branch implementing a `src-layout`  version of bip-utils to investigate why conda recipe fails for some versions of python. FYI: https://github.com/MementoRC/bip_utils/pull/1

This issue is resolved to my satisfaction, thanks a lot  for your consideration and taking the time

**Comment by ebellocchia** [comment]
That's strange because that only happens with `ecdsa<=0.16` (bw, in that case the `AttributeError` is catched in the code, but for some reasons doesn't work), but with `ecdsa>=0.17` like now it shall not happen
